{{/* Append the hardcoded settings */}}
{{- define "memos.harcodedValues" -}}
env:
  MEMOS_PORT: {{ .Values.service.main.ports.http.port }}

  {{- if .Values.postgresql.enabled }}
  {{- with .Values.postgresql }}
  MEMOS_DRIVER: postgres
  DB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-postgresql
      key: {{ if not .auth.password }}postgres-{{ end }}password
  MEMOS_DSN: postgresql://{{ default "postgres" .auth.username }}:$(DB_PASSWORD)@{{ $.Release.Name }}-postgresql/{{ .auth.database }}?sslmode=disable
  {{- end }}
  {{- else if .Values.mariadb.enabled }}
  {{- with .Values.mariadb }}
  MEMOS_DRIVER: mysql
  DB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-mariadb
      key: mariadb-password
  MEMOS_DSN: {{ .auth.username }}:$(DB_PASSWORD)@tcp({{ $.Release.Name }}-mariadb)/{{ .auth.database }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "memos.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
