apiVersion: v2
name: borgmatic
description: borgmatic is simple, configuration-driven backup software for servers and workstations. Protect your files with client-side encryption. Backup your databases too. Monitor it all with integrated third-party services.
home: https://charts.gabe565.com/charts/borgmatic
icon: https://raw.githubusercontent.com/borgmatic-collective/borgmatic/1.6.6/docs/static/borgmatic.svg
type: application
version: 0.6.5
# renovate datasource=docker depName=ghcr.io/borgmatic-collective/borgmatic
appVersion: 1.7.8
kubeVersion: ">=1.21.0-0"
keywords:
  - borgmatic
  - borg
  - backup
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/gabe565/charts/tree/main/charts/borgmatic
  - https://projects.torsion.org/borgmatic-collective/borgmatic
  - https://github.com/borgmatic-collective/docker-borgmatic
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/borgmatic-collective/borgmatic Docker tag to v1.7.8
