#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/linuxserver/plex
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: version-1.32.0.6950-8521b7d99

# -- Environment variables. [[ref]](https://github.com/linuxserver/docker-plex#parameters)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Set the container timezone
  TZ: UTC

service:
  # -- Configures HTTP service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 32400

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  config:
    enabled: false
    retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 16Gi
  # -- Configure media volume under this key (or under `tv` and `movies`, etc).
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: false
    # type: nfs
    # server:
    # path:
