#!/usr/bin/env bash
set -euo pipefail
export IFS=$'\n\t'

repo_path="${1:-https://github.com/gabe565/charts}"

cd "$(git rev-parse --show-toplevel)"

cp README.md docs/src/README.md

CHARTS=()

# Copy readmes
while IFS= read -r -d '' f; do
  mkdir -p "docs/src/$(dirname "$f")"

  sed '/^\*\*Homepage:\*\*/,+1d' "$f" \
    | sed "s|(\./\(.*\.yaml\))|($repo_path/blob/main/$(dirname "$f")/\1)|g" \
    > "docs/src/$f"

  CHARTS+=("$(basename "$(dirname "$f")")")
done < <(find charts -type f -name '*.md' -not -path './docs/*' -print0)

CHARTS=( $(printf '%s\n' "${CHARTS[@]}" | sort -h) )

# Add charts to sidebar
{
    echo '<!-- Generated by hack/prepare-docs.sh -->'
    cat docs/src/.SUMMARY_src.md
    for chart in "${CHARTS[@]}"; do
        echo "  - [$chart](charts/$chart/README.md)"
    done
} > docs/src/SUMMARY.md
