#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: vabene1111/recipes
  # -- image tag
  tag: 1.4.6
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag

# -- environment variables. [[ref]](https://github.com/TandoorRecipes/recipes/blob/master/.env.template).
# @default -- See [values.yaml](./values.yaml)
env:
  # -- default timezone
  TIMEZONE: UTC
  # SECRET_KEY: changeme

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080
      static:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
          - path: /static
            service:
              port: 80
          - path: /media
            service:
              port: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See [values.yaml](./values.yaml)
persistence:
  config:
    enabled: false
  media:
    enabled: false
    mountPath: /opt/recipes/mediafiles
  static:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/staticfiles

# -- Enable and configure postgresql database subchart under this key. [[ref]](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: false
  auth:
    database: tandoor
    postgresPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi
