apiVersion: v2
name: adguard-home
description: Free and open source, powerful network-wide ads & trackers blocking DNS server.
home: https://charts.gabe565.com/charts/adguard-home/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/adguard-home/icon.svg
type: application
version: 0.3.3
# renovate datasource=docker depName=adguard/adguardhome
appVersion: v0.107.33
kubeVersion: ">=1.22.0-0"
keywords:
  - adblock
  - dns
  - privacy
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
sources:
  - https://github.com/AdguardTeam/AdGuardHome
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update adguard/adguardhome Docker tag to v0.107.32
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/AdguardTeam/AdGuardHome
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/adguard-home
