{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
