#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/gabe565/transsmute
          # -- image pull policy
          pullPolicy: Always
          # -- image tag
          tag: latest

        # -- environment variables. [[ref]](https://github.com/gabe565/transsmute#configuration)
        # @default -- See [values.yaml](./values.yaml)
        env: {}
          # TRANSSMUTE_YOUTUBE_KEY: ""
          # TRANSSMUTE_DOCKERHUB_USERNAME: ""
          # TRANSSMUTE_DOCKERHUB_PASSWORD: ""
          # TRANSSMUTE_GHCR_USERNAME: ""
          # TRANSSMUTE_GHCR_PASSWORD: ""

        # -- Container security context.
        securityContext:
          readOnlyRootFilesystem: true

    # -- Set the controller upgrade strategy
    strategy: RollingUpdate

    pod:
      # -- Pod security context.
      securityContext:
        runAsNonRoot: true

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         service:
    #           name: main
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local
