apiVersion: v2
name: esphome
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
home: https://charts.gabe565.com/charts/esphome/
icon: https://raw.githubusercontent.com/esphome/esphome-docs/0191785/images/logo.svg
type: application
version: 0.15.0
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - home-automation
  - home-assistant
  - esp8266
  - esp32
  - iot
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.3
sources:
  - https://github.com/esphome/esphome
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Unpin image tag
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/esphome/esphome
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/esphome
