#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/esphome/esphome
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2023.5.3

# -- Environment variables.
# @default -- See [values.yaml](./values.yaml)
env: {}
  # ESPHOME_DASHBOARD_USE_PING: "true"
  # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HA_ADDON:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 6052

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

# -- Configure persistence settings for the chart under this key.
# @default -- See [values.yaml](./values.yaml)
persistence:
  config:
    enabled: false
    retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 4Gi

# dnsConfig:
#   nameservers: []
# dnsPolicy:

addons:
  codeserver:
    # -- Enable VS Code server addon.
    #    This allows for easy access to device configuration
    enabled: false
    # -- Enable and configure ingress settings for the VS Code server under this key.
    # @default -- See [values.yaml](./values.yaml)
    ingress:
      enabled: false
      # hosts:
      #   - host: code.chart-example.local
      #     paths:
      #       - path: /
      # tls:
      #   - secretName: code.chart-example.local-tls
      #     hosts:
      #       - code.chart-example.local
    # @ignored
    args:
      - --auth=none
      - --user-data-dir=/data/config/.vscode
    # @ignored
    volumeMounts:
      - name: config
        mountPath: /data/config
