#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository.
  repository: ghcr.io/gabe565/ascii-movie
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: 1.5.2

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- Environment variables. [[ref]](https://github.com/gabe565/ascii-movie/blob/main/docs/ascii-movie_serve.md)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Number of concurrent streams allowed from an IP address. Set to 0 to disable.
  ASCII_MOVIE_CONCURRENT_STREAMS: 10
  # ASCII_MOVIE_SPEED:

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      http:
        enabled: false
        primary: false
      ssh:
        enabled: true
        port: 22
      telnet:
        enabled: true
        primary: true
        port: 23
  api:
    enabled: true
    ports:
      http:
        enabled: true
        port: 1977

secrets:
  ssh:
    # -- Enables SSH host key volume.
    # @default -- `true` if SSH port is enabled, else `false`
    enabled:
    stringData:
      # -- (string) SSH Ed25519 host key.
      # @default -- Generated
      ssh_host_ed25519_key:
      # -- (string) SSH RSA host key.
      # @default -- Generated
      ssh_host_rsa_key:
