#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository.
  repository: ghcr.io/gabe565/ascii-movie
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: 1.2.1

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      http:
        enabled: false
        primary: false
      ssh:
        enabled: true
        port: 22
      telnet:
        enabled: true
        primary: true
        port: 23
